version: '3.8'

services:
  # 1. Cơ sở dữ liệu PostgreSQL
  db:
    image: postgis/postgis:16-3.4-alpine
    container_name: my-postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}    
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: app_db          
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 

  pgadmin:
    image: dpage/pgadmin4
    container_name: my-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}      
    ports:
      - "5050:80"
    depends_on:
      - db

  # 3. Backend Spring Boot (Tùy chọn: nếu muốn chạy cả app trong Docker)
  app:
    build:
      context: .
      dockerfile: Dockerfile # Trỏ vào file Dockerfile mới tạo
    container_name: spring-boot-backend
    ports:
      - "8080:8080"
    env_file:          
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/app_db
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: spingboot123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
       - .:/app
       - /app/.mvn
       - /app/target
    command: ./mvnw spring-boot:run
    depends_on:
      - db
volumes:
  postgres_data:
